### ISSUE TITLE
preferred way to make blank part?

### ISSUE THREAD

**Issue by ipsod** [jeff-dh/SolidPython#1]
I've found it useful to start parts off with part().  This lets me comment-out/move/etc. the first item, just like I can the rest of them.

Example:
```
thing = part()
thing += cube([10, 10, 10])
thing += right(10)(cube([5, 5, 5]))
```

Since your fork doesn't support part(), what would be the preferred way to make a blank part?

**Comment by jeff-dh** [comment]
I would suggest to use a "native OpenSCAD container" because that's what it actually is, right?

```python
>>> from solid import *
>>> a = union()
>>> a += cube(5)
>>> a += sphere(1)
>>> a
union() {
        cube(size = 5);
        sphere(r = 1);
}
```

If you don't want a `union`, you can do the same with a `difference` or `intersection`.

**Comment by jeff-dh** [comment]
Btw: If you really really want or need to, you can import the legacy-extension and continue using `parts`. But I would strongly recommend to explicitly use `union,difference` and `intersection` instead like mentioned above.

```python
>>> from solid import *
>>> from solid.extensions.legacy import *
>>> p = part()
>>> p += cube(1)
>>> p += sphere(1)
>>> p
union() {
        cube(size = 1);
        sphere(r = 1);
}
```

(This might be a good solution to get (your) old code running without changes except for the import)

**Comment by ipsod** [comment]
`union` makes more sense.  Thank you!
