### ISSUE TITLE
Support BOSL2 screws.screw_hole

### ISSUE THREAD

**Issue by ssuchter** [jeff-dh/SolidPython#18]
This code doesn't work:

```
screws.screw_hole("6-32", length=height / 25.4)
```

It gets this error message:

AttributeError: module 'solid2.extensions.bosl2.screws' has no attribute 'screw_hole'. Did you mean: 'screw_head'?

**Comment by ssuchter** [comment]
It seems like the problem is that the BOSL2 code is pasted into this repo, with an old version.

Is this the desired practice? Or should this be using another mechanism, like git Submodules?

**Comment by jeff-dh** [comment]
Should be fixed (updated to latest BOSL2 HEAD + integrated as submodule)

**Comment by ssuchter** [comment]
Thanks! I updated to the latest from master-2.0.0-beta-dev. When I used a pip local dist build and then install, it didn't install the BOSL2 lib files:

```
GWLW4HPQVR:~% pip show solidpython2
Name: solidpython2
Version: 2.0.0
Summary: Python interface to the OpenSCAD declarative geometry language
Home-page: https://github.com/jeff-dh/SolidPython
Author: jeff
Author-email:
License: LGPL-2.1
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: ply, setuptools
Required-by:
GWLW4HPQVR:~% ls /opt/homebrew/lib/python3.10/site-packages/solid2/libs
__init__.py   __pycache__   py_scadparser
```

I suspect something needs to be updated in packaging steps?

**Comment by jeff-dh** [comment]
Give it another try....

**Comment by ssuchter** [comment]
Works now, thanks.

I see that you re-added things as files, instead of as a submodule. If I could make it work with a submodule (but still installing a snapshot of BOSL), would you like a PR for that?

**Comment by jeff-dh** [comment]
Yeah, sure.

**Comment by ssuchter** [comment]
Question about your workflow: When you build the pip package do you do it via 'poetry build' or via 'python -m build' or something else?

**Comment by jeff-dh** [comment]
I use `poetry build`.

**Comment by ssuchter** [comment]
Here you go: https://github.com/jeff-dh/SolidPython/pull/19

**Comment by ssuchter** [comment]
Closing this issue, as BOSL2 has been updated in master-2.0.0-beta-dev
