### ISSUE TITLE
Maybe inappropriate default value in scale* functions？

### ISSUE THREAD

**Issue by senventise** [jeff-dh/SolidPython#26]
For example, the [current](https://github.com/jeff-dh/SolidPython/blob/ee7d03c028ff7dcd86f118715affcf0f873388fe/solid2/core/builtins/convenience.py#L49) `scaleX` function returns `scale((x, 0, 0))` instead of `scale((x, 1, 1))`, makes the object disappear.

**Comment by jeff-dh** [comment]
should be fixed in the latest head.

I will not publish a pypi package for this fix right now, because there is some more work going on atm and I'd rather release a pypi package soon containing several changes.
