### ISSUE TITLE
prebuild.py call causes "build error"

### ISSUE THREAD

**Issue by jeff-dh** [jeff-dh/SolidPython#27]
https://github.com/jeff-dh/SolidPython/blob/4337922c5535f9d564bd7ac15d733e98f6f3a948/pyproject.toml#L45

For some reason this causes this error over here when I call `poetry build`:

```$poetry build
Preparing build environment with build-system requirements poetry-core>=1.0.0
Building solidpython2 (2.0.1)
Traceback (most recent call last):
  File "/[..]/SolidPython/setup.py", line 2, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

Command '['/tmp/tmpkz3ceeao/.venv/bin/python', '/[..]/SolidPython/setup.py', 'build', '-b', '/[..]/SolidPython/build']' returned non-zero exit status 1.


```
Note: setuptools is installed

changing the pyproject.toml file like this:

```python
[tool.poetry.build]
generate-setup-file = false
script = "prebuild.py"
```
makes the call work again, but the build process creates a different file!?! `solidpython2-2.0.1-cp310-cp310-manylinux_2_35_x86_64.whl` instead of `solidpython2-2.0.1-py3-none-any.whl`

@ssuchter Any idea what's going on there?

**Comment by jeff-dh** [comment]
maybe related:

https://github.com/python-poetry/poetry/pull/5401

**Comment by ssuchter** [comment]
Hm, I don't think we need the setup.py file, so how about we just keep the
generate-setup-file = false line?

I saw that in the examples I looked at (having the generate-setup-file =
false) but it worked in my setup, so I didn't think it was important and
opted for a shorter change. But if it's breaking your setup, I vote for
just fixing it by including the option, without figuring out why.

**Comment by jeff-dh** [comment]
Well but as mentioned, the output is different. Why is the wheel
file a different (at least the name which seems to be less portable,
at least the name says so).

**Comment by ssuchter** [comment]
Hm, I need to try to reproduce your problem. I'll try.

**Comment by jeff-dh** [comment]
Do you have all necessary information?

If you remove the whole `[tool.poetry.build]` section, it creates a *py3-none-any.whl file (as it used to be). With the prebuild.py call and `generate-setup-file = false` it produces *cp310-cp310-manylinux_2_35_x86_64.whl which is according to [this](https://peps.python.org/pep-0491/#file-name-convention) less compatible.

Does it behave the same on your system?

**Comment by ssuchter** [comment]
I'll take a look tonight (California time)

**Comment by ssuchter** [comment]
Ok, I've reproduced the issue, looked through poetry code, and found that for some bizarre reason, poetry doesn't support using a build script and producing a pure python wheel. Others complain about the same issue:

https://github.com/python-poetry/poetry/issues/2051

I'm trying a workaround from that issue now.

**Comment by ssuchter** [comment]
I think the lack in underlying poetry is hard to work around. I think the right thing to do is to not use the prebuild script. Originally, it was being used to autogenerate stubs, but you changed my mind on that. Now it's just validating that the submodules got initialized, but we can use the tests to validate that now. I'll make a PR for this trivial change.

**Comment by ssuchter** [comment]
Here's the PR for you: https://github.com/jeff-dh/SolidPython/pull/28
