### ISSUE TITLE
Missing BOSL2 libraries.

### ISSUE THREAD

**Issue by j-d-salinger** [jeff-dh/SolidPython#32]
You are missing functions like pie_slice, etc

Why are you missing the one BOSL2 code that I need?

**Comment by j-d-salinger** [comment]
Classic - it is in the github repo, but not the pypi release

**Comment by jeff-dh** [comment]
It's supposed to be there (in the pypi package)!

Which version are you using?

This is how it's supposed to be:

```python
>>> from solid2.extensions.bosl2.shapes3d import pie_slice
>>> pie_slice
<class 'solid2.extensions.bosl2.shapes3d.pie_slice'>
```

**Comment by j-d-salinger** [comment]
Python 3.9.2, idk man

**Comment by jeff-dh** [comment]
Which version of the SolidPython PyPi package (`pip show solidpython2`)

**Comment by j-d-salinger** [comment]
It's gone... It can never come back.... Jk... I really don't want to break my system though by trying to re-install this.... If the drive crashes again and I have to reinstall all my dependencies, I'll come back here and update you
