### ISSUE TITLE
Unable to union shapes with modifiers

### ISSUE THREAD

**Issue by aldencolerain** [jeff-dh/SolidPython#35]
Shapes with modifiers can be unioned in OpenSCAD, but this does not work as expected in SolidPython. This is my first time using SolidPython, so I may be missing something basic.

This works:
```
#! /usr/bin/env python

from solid2 import *

geo = cube(1).debug() + cube(1).translate(1, 1, 0)
geo.save_as_scad()
```

This doesn't work:
```
#! /usr/bin/env python

from solid2 import *

geo = cube(1).debug() + cube(1).translate(1, 1, 0).debug()
geo.save_as_scad()
```

It fails with the error:
```
TypeError: unsupported operand type(s) for +: 'debug' and 'debug'
```

**Comment by jeff-dh** [comment]
That was indeed a bug.

Should be fixed in the latest head.....

**Comment by aldencolerain** [comment]
Thank you!
