### ISSUE TITLE
Convenience methods + operators are not recognized by pyright

### ISSUE THREAD

**Issue by elentok** [jeff-dh/SolidPython#4]
First, I just wanna say thanks for all the hard work, I've been using SolidPython for a while and loving it :-)

One thing that is a bit of an annoyance is many warnings when I use the pyright LSP, it doesn't recognize the monkey patched extensions to `ObjectBase`. See the screenshot:

![image](https://user-images.githubusercontent.com/1129276/187472428-54869783-2604-4454-94ab-8b1ba47f0348.png)

I saw [this issue][1] on the pylance project (the VSCode extension that uses pyright) which seems to mean they're no going to support it probably :-(

I tried adding these imports to see if it might recognize the extensions but it didn't work:

```py
from solid2.extensions.access_syntax import __nothing__
from solid2.extensions.operators import __nothing__
```

I was wondering if have any thoughts/plans on this?

Thanks again,
David.

[1]: https://github.com/microsoft/pylance-release/issues/2335

**Comment by jeff-dh** [comment]
I was already afraid something like that could pop up at some point.

I don't have any thoughts about it yet, but let me think about it for a couple of days, I'll try to come up with something....

**Comment by jeff-dh** [comment]
checkout the branch mentioned above
(https://github.com/jeff-dh/SolidPython/tree/no_more_objectbase_patching)

I think it should fix your issue.

I'm not 100% convinced by it yet (because of some architectural issues) but I think that's the path to go.

I'll think about it a little more, but I'll probably gonna merge it into master soon.

**Comment by jeff-dh** [comment]
Btw:

After thinking for it for a while now, I still don't like the archtectual design of the fix and therefor I'm not motivated to merge it into the master. At the same time I don't have any other idea how to fix this issue.......

I would leave this issue open for now and the branch with the fix as a separate branch.

**Comment by jeff-dh** [comment]
I'm just playing around with modern editor stuff including lsps and figured out, that the [python-lsp-server](https://github.com/python-lsp/python-lsp-server) does not have this issue!

So if you're able to try to switch to python-lsp-server instead of pyright.
