### ISSUE TITLE
Unable to pass numpy scalars to builtins

### ISSUE THREAD

**Issue by mraleson** [jeff-dh/SolidPython#41]
It looks like numpy numbers can't be used in cube etc because of the int/float type check.

```python
import numpy
from solid2 import *

# geometry = cube(1, 2, 3)
geometry = cube(numpy.float32(1), 2, 3)
geometry.save_as_scad()
```

https://github.com/jeff-dh/SolidPython/blob/eb5602a2c917fb809a4f0b77e5322a4cb8ee8acc/solid2/core/builtins/convenience.py#L85

May be possible to check numeric types `numbers`, I'm not sure if this has any negative side effects:
```python
import numbers
isinstance(a, numbers.Number)
```

**Comment by jeff-dh** [comment]
I think `numbers.Real` makes more sense than `numbers.Number`......

Thx!
