### ISSUE TITLE
Passing a bosl2 object to the polygon class throws an 'object not iterable' error.

### ISSUE THREAD

**Issue by edog1973** [jeff-dh/SolidPython#47]
Sample Code
```
from solid2 import *
import solid2.extensions.bosl2.rounding as rounding

points =[ [0,0], [100,0], [50,100]]
points = rounding.round_corners(points, radius=10)

poly = polygon(points=points)

o = poly.linear_extrude(height=2)

o.save_as_scad("test.scad")
```
 Throws error:
```
Traceback (most recent call last):
  File "/home/ericw/This Old Part/Working/JSHC92 - 92-96 Jump Seat Hinge Covers/Model/test.py", line 10, in <module>
    poly = polygon(points=points)
  File "/home/ericw/code/solidpython/lib/python3.10/site-packages/solid2/core/builtins/openscad_primitives.py", line 47, in __init__
    pts = list([(p[0], p[1]) for p in points]) # type: ignore
TypeError: 'round_corners' object is not iterable
```

The polygon init method checks if the the points parameter is an instance of OpenSCADObject to determine if it should be passed through or iterated.  The rounding_corners BOSL2 function returns a class that is not a subclass of OpenSCADObject.  Modifying the polygon init method to check for BareOpenSCADObject seems to resolve the issue, but I do not know if this would cause other problems.

**Comment by jeff-dh** [comment]
Great, thanks!

Should be fixed in master-.....

Will be contained in the next release (2.1) which might take a some more time because blablub.... (talking about a couple weeks maybe)
