### ISSUE TITLE
How would one `include` external libraries?

### ISSUE THREAD

**Issue by dneise** [jeff-dh/SolidPython#51]
Hey there! 
I've not yet started with openScad, but am still looking around and found your awesome project.

I found that openScad supports external libraries, like e.g. these chamfered primitives https://github.com/SebiTimeWaster/Chamfers-for-OpenSCAD

In oder to use them in the openScad lang one needs to [`include <Chamfers-for-OpenSCAD/Chamfer.scad>;`](https://github.com/SebiTimeWaster/Chamfers-for-OpenSCAD/tree/master#usage). Now I wonder how and if this translates to Python?

For sure, we cannot simply do:
```python
from Chamfers-for-OpenSCAD import Chamfer

Chamfer.chamferCube(...)
```

Have a great day and thanks a lot!

**Comment by jeff-dh** [comment]
https://github.com/jeff-dh/SolidPython/blob/master-2.0.0-beta-dev/solid2/examples/07-libs.x.py

Furthermore solidpython has a relative new feature which even supports `from chamfer_lib import Chamfer` checkout 
https://github.com/jeff-dh/SolidPython/blob/master-2.0.0-beta-dev/solid2/extensions/openscad_extension_generator.py

But I would suggest to take look at the built in bosl2 library first. It includes a whole lot of stuff (and is built in and the bosl2 support is pretty good I think).

**Comment by jeff-dh** [comment]
![solid2-chamfer](https://github.com/jeff-dh/SolidPython/assets/1105041/57f2b1e7-bb2c-4ffc-979e-a4ded2b582a6)

**Comment by dneise** [comment]
Thanks so much! I think we can close this
