### ISSUE TITLE
fill() function from dev snapshot not supported

### ISSUE THREAD

**Issue by jonboh** [jeff-dh/SolidPython#53]
I think the [fill()](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#fill) function from the dev snapshot is still not supported by solidpython2, but is it possible to add an arbitrary function so that the generated code has it? Even if the library itself does not know about it.

Are you planning to implement fill()?

**Comment by jeff-dh** [comment]
you can create an extension for it. Create file called `fill_extension.py` with this content:

```python
from solid2 import register_access_syntax
from solid2.core.object_base import OpenSCADObject

@register_access_syntax
class fill(OpenSCADObject):
    def __init__(self) -> None:
        super().__init__('fill', {})
```

Afterwards you can use it like this:

```python
>>> from solid2 import circle
>>> import fill_extension
>>> circle().fill()
fill() {
        circle();
}
```

LSP support will not work for such extensions.
