### ISSUE TITLE
Suggestion for a sample code in wiki page (2D text 'box' to 3D)

### ISSUE THREAD

**Issue by iobataya** [jeff-dh/SolidPython#56]
Hi, I appreciate this project and enjoy with it.

When I ran sample code In wiki page, I got the following warnings due to 2D object is mixed with 3D objects.
> [WARNING: Mixing 2D and 3D objects is not supported in file 
> [WARNING: Ignoring 2D child object for 3D operation in file

Linear_extruding a 2D text 'box' will fix this, showing ellegance of solidpython.
```
label = text('box').linear_extrude(height=1).translate(5, 5, 5)
```

**Comment by jeff-dh** [comment]
:+1:

My next solidpython session will consider this!

**Comment by jeff-dh** [comment]
(finally "fixed")
