### ISSUE TITLE
add support for manifold and openscad-nightly

### ISSUE THREAD

**Issue by bat52** [jeff-dh/SolidPython#65]
Manifold option allowing multi-threading, and resulting in significant performance improvements, has been integrated in openscad. 
https://github.com/openscad/openscad/issues/391#issuecomment-1718145488

It would be great if solidpython could make use of this option.
For instance:
`openscad --enable=manifold -o out.stl in.scad`

Additionally, while the feature is available since 2022, ubuntu official repos still deliver an openscad version that dates back to 2021.
Alternatively it is possible to install a nightly build snap
`snap install openscad-nightly`
but that requires running the command "openscad-nightly' instead of openscad.

**Comment by jeff-dh** [comment]
please take a look at #53

**Comment by bat52** [comment]
Here an example of how to add/override class methods locally without modifying the core components https://github.com/jeff-dh/SolidPython/issues/53

**Comment by jeff-dh** [comment]
you should be able to use it "out of the box" if you save your model as scad file and run openscad afterwards.

What's not working out of the box is `save_as_stl`. This would need a configuration value for parameters to be passed to the openscad execution. I'll might have a look at it at some time.

**Comment by bat52** [comment]
Well in the end I realized I do not even know this, because I have a wrapper class, so I can export .scad file and covert to .stl with a custom command that I can define.
https://github.com/bat52/pylele/blob/main/api/sp2_api.py#L78

For the time being I am detecting the openscad version from shell call from which I can know if the manifold option is available.
I guess I could create an alias to redirect openscad calls to openscad-nightly, but I have not tried this yet.

Is there any performance loss in first exporting .scad, then convert .scad to .stl , versus exporting directly in .stl?

**Comment by jeff-dh** [comment]
5f2c987 should fix this issue 

```python
>>> from solid2.config import config
>>> config.openscad_stl_command = "openscad-nightly --enable=manifold -o {stlfile} {scadfile}"
>>> 
>>> from solid2 import cube
>>> cube(1).save_as_stl()
Traceback (most recent call last):
[...]
FileNotFoundError: [Errno 2] No such file or directory: 'openscad-nightly'
>>> 
```

reopen if there are any further issues.
