### ISSUE TITLE
Need a way to name entities 

### ISSUE THREAD

**Issue by shreekumar3d** [jeff-dh/SolidPython#67]
I am looking for a way to get SolidPython to output a scad "module". I need this so that the scad output clearly shows the logic used to create the scene.  My scene consists of a booleans that operate on extruded polygons with lots of vertices.  Right now, the polygon coordinates are replicated.

As an example,
```
need_a_name = polygon([[0,0],[0,1],[0,1]])
s1 = need_a_name.linear_extrude(10)
s2 = need_a_name.linear_extrude(5).right(10)
s3 = s1+s2
print(s3)
```
would replicate the polygon coordinates twice.

I am looking to achieve the following output
```
module need_a_name() {
        polygon(points = [[0, 0], [0, 1], [0, 1]]);
}
union() {
	linear_extrude(height = 10) {
                need_a_name();
	}
	translate(v = [10, 0, 0]) {
		linear_extrude(height = 5) {
                        need_a_name(); 
                }
	}
}
``` 

Any way this can be done in SolidPython2 ?

**Comment by jeff-dh** [comment]
https://github.com/SolidCode/SolidPython/issues/197#issuecomment-1142865675

**Comment by shreekumar3d** [comment]
Thanks @jeff-dh ! I added [a comment](https://github.com/SolidCode/SolidPython/issues/197#issuecomment-2424904674) in reply to SolidCode#197 . That issue is closed, but my comment provides better context there I feel.
