### ISSUE TITLE
How to view solid2 objects in Juypter lab

### ISSUE THREAD

**Issue by jreiberkyle** [jeff-dh/SolidPython#7]
I am able to view `solid` objects with `viewscad` in Jupyter lab but I can't figure out how to render `solid2` objects. Is there some change I need to make beyond replacing `solid.<geom>` with `solid2.<geom>`?

Note that running `viewscad.Renderer().render(solid2.cylinder(r=5, h=2))` has empty output while `viewscad.Renderer().render(solid.cylinder(r=5, h=2))` shows the 3d view. It appears that `solid2.cylinder(r=5, h=2).__repr__()` outputs scad code, which is useful but unfortunately not the 3d view.

![image](https://user-images.githubusercontent.com/2984664/211095121-781e0b39-7324-4c3f-9b91-9e905907b5c1.png)

Relevant package versions:
jupyter                  1.0.0
solidpython              1.1.3
solidpython2             2.0.0b1
viewscad                 0.2.0

**Comment by jreiberkyle** [comment]
Ok with some investigation it appears the limitation is with viewscad. Makes sense, the repo hasn't been updated in 4 years. I was able to get viewscad and solidpython2 working by just updating viewscad's dependency to solidpython2 and then importing solid2 as solid in my (hacked) working version [here](https://github.com/jreiberkyle/ViewSCAD). If my reasoning is correct, you may want to consider updating the docs to indicate that solidpython2 and the viewscad pypi package are not compatible.

**Comment by jeff-dh** [comment]
Yeah, I agree about updating the readme.

Do you have a proposal? I guess mentioning your branch and.... (I've never been in touch with viewscad at all).

If you like to make any suggestions and create a PR.......

**Comment by jeff-dh** [comment]
I added two sentences to the readme summarizing your results and linked your fork and this issue.

My support for this topic is limited, since I don't use jupyter notebooks at all. Suggestions, PRs,... are welcome!

**Comment by kylekyle** [comment]
I love designing STLs using Jupyter/SolidPython in VSCode, so I'd be interested in making this work. 

I think viewscad should just be baked into solid2. ViewSCAD is a single python file. If you just replace all instances of `solid` with `solid2`, it works. Then we can simply add a `#render` method `OpenSCADObject`.  If @jeff-dh is interested in a pull request, I can make one.

**Comment by jreiberkyle** [comment]
@kylekyle you should check out [jupyterscad](https://github.com/jreiberkyle/jupyterscad) - just `pip install jupyterscad`. Works like ViewSCAD but supports SolidPython2, integrating external stl's, and a bit more control over visualization. Check out the bottom of the README (edit: [link](https://github.com/jreiberkyle/jupyterscad#transitioning-from-viewscad)) for how to move from ViewSCAD to jupyterscad. I need to talk to @jeff-dh about switching the recc over from my viewscad fork to jupyterscad

**Comment by jeff-dh** [comment]
@jreiberkyle 
https://github.com/jeff-dh/SolidPython/wiki/JupyterLab-Notebook-support

like this ok or would you like anything else / more?

**Comment by jeff-dh** [comment]
We could add a minimalistic example to the SolidPython2 docs / wiki:

Install JupyterSCAD:
```
pip install jupyterscad
```

```python
from solid2 import cube
from jupyterscad import render

obj = cube(1, 2, 3)
render(obj)
```

That's all, right?

PS: can't test the code because I don't use jupyter notebooks at all....

Btw: the jupyterscad README uses `import jupyter_scad` instead of `import jupyterscad` (I guess that's outdated, right?)

**Comment by kylekyle** [comment]
Jupyter SCAD is exactly what I was looking for! Don't know how I missed it. Thanks for pointing me in the right direction! 

An example in the wiki is a good call since at the moment a Google search for "solidpython jupyter" only returns information about viewscad.

**Comment by jreiberkyle** [comment]
@jeff-dh that looks great. BTW what is the "Lite" for in JupyterLab Lite Notebook Support?

@kylekyle I'm glad you are finding it useful! I just recently created the project so I can understand why it isn't yet very discoverable. I expect the primary audience will discover it through SolidPython2 docs.

**Comment by jeff-dh** [comment]
On Sun, 15 Oct 2023 14:49:13 -0700
Jennifer Reiber Kyle ***@***.***> wrote:

> @jeff-dh that looks great. BTW what is the "Lite" for in JupyterLab
> Lite Notebook Support?

While having a look at it I came across JupyterLite (and tried to make
solidpython and jupyterscad work in it, but unfortunately but obviously
openscad is missing....)

https://jupyter.org/try-jupyter/lab/

"JupyterLite is a JupyterLab distribution that runs entirely in the
browser built from the ground-up using JupyterLab components and
extensions."

I'm gonna remove it.

**Comment by jreiberkyle** [comment]
> Btw: the jupyterscad README uses import jupyter_scad instead of import jupyterscad (I guess that's outdated, right?)

ahh! great catch! fixed here: https://github.com/jreiberkyle/jupyterscad/pull/7

**Comment by jreiberkyle** [comment]
JupyterLite looks very cool! It makes me wish for something like OpenSCAD As A Service. An alternative web notebook interface that allows for installing openscad is google colab. Throws an interesting error I'll have to look into but still renders and provides interactivity.

![image](https://github.com/jeff-dh/SolidPython/assets/2984664/6bab9c27-84af-4c16-9426-52da2e2bc30a)
